# Generated by Django 4.0.4 on 2022-05-12 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbase',
            name='USER_MMID',
            field=models.CharField(default='', max_length=100),
        ),
    ]
